const data = [
  {
    name: "HigherEd Horizon: Pioneering Education Excellence",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "",
    pcc_due_meeting_date: "",
    certification_stage: "",
    certifications_stage_due_date: "",
    id: 1,
  },
  {
    name: "Court Harmony: Supreme Court Comission Endeavor",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "",
    pcc_due_meeting_date: "",
    certification_stage: "PCC Review Approved",
    certifications_stage_due_date: "",
    id: 2,
  },
  {
    name: "DPS: Reinventing Public Safety through Advanced Technology",
    approved_phase: "Initiation",
    pending_certification_phase: "",
    pcc_due_meeting_date: "",
    certification_stage: "",
    certifications_stage_due_date: "",
    id: 3,
  },
  {
    name: "RetireGuard: Safeguarding Public Servants' Futures with the Retirement Association",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "",
    pcc_due_meeting_date: "",
    certification_stage: "",
    certifications_stage_due_date: "",
    id: 4,
  },
  {
    name: "Complete end to end Flow",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "Planning/Implementation",
    pcc_due_meeting_date: "28 May 2024",
    certification_stage: "EPMO Review Pending",
    certifications_stage_due_date: "09 May 2024",
    id: 5,
  },
  {
    name: "EmpowerAbility: Enhancing Accesibility and Inclusion for Persons with Disabilites",
    approved_phase: "",
    pending_certification_phase: "Initiation",
    pcc_due_meeting_date: "28 May 2024",
    certification_stage: "EPMO Review Pending",
    certifications_stage_due_date: "09 May 2024",
    id: 6,
  },
  {
    name: "Tourism Industry IT Infrastructure Project 2024",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "Inititation",
    pcc_due_meeting_date: "28 May 2024",
    certification_stage: "EPMO Review Pending",
    certifications_stage_due_date: "09 May 2024",
    id: 7,
  },
  {
    name: "The Taxation & Revenue Dept- Modernization Project",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "Planning",
    pcc_due_meeting_date: "",
    certification_stage: "",
    certifications_stage_due_date: "",
    id: 8,
  },
  {
    name: "The Dept of Information Technology- Statewide Integrated Radio Communication",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "Planning",
    pcc_due_meeting_date: "28 May 2024",
    certification_stage: "PCC Review Pending",
    certifications_stage_due_date: "09 May 2024",
    id: 9,
  },
  {
    name: "Journey Vista: State Tourism Thrive Initiative",
    approved_phase: "Initiation Approved",
    pending_certification_phase: "",
    pcc_due_meeting_date: "26 June 2024",
    certification_stage: "EPMO Review Pending",
    certifications_stage_due_date: "07 June 2024",
    id: 10,
  },
];

export default data;
